version: '2'
services:
  master:
    build: .
    container_name: master
    command:
      - roscore

  talker:
    build: .
    container_name: audio
    environment:
      - "ROS_HOSTNAME=audio"
      - "ROS_MASTER_URI=http://master:11311"
    command: candybot_ros-dev apps nodes candybot_audio

  listener:
    build: .
    container_name: speech
    environment:
      - "ROS_HOSTNAME=speech"
      - "ROS_MASTER_URI=http://master:11311"
    command: candybot_ros-dev apps nodes candybot_speech

